### ISSUE TITLE
Can't Update VNF Metadata

### ISSUE THREAD

**Issue by rafael-direito** [openslice/io.openslice.portal.api#16]
When editing a VNF's metadata, Openslice returns the following message: `- Failed to update VNF! Cannot read the array length because "<local11>" is null`. See image below:

![Screenshot 2023-09-27 at 15 16 17](https://github.com/openslice/io.openslice.portal.api/assets/30239227/d2c928a1-40b6-4723-a90b-1daaf1fdb3ec)

After carefully inspecting the logs of the different components, I found out that the issue is related to the Portal API, which presents the following error:

```
12:13:52.216 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - checkUserIDorIsAdmin, authentication role =  true
12:13:52.216 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - Received @PUT for vxf : yogoko_CITS_NetApp_vnf3
12:13:52.216 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - Received @PUT for vxf.extensions : []
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - userid = 2
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - prodname = yogoko_CITS_NetApp_vnf3
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - prodid = 1
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - produuid = 6c5d2095-a348-425b-a42a-10fa6f931946
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - version = 1.0
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - shortDescription = yogoko_CITS_NetApp_vnf3
12:13:52.217 [http-nio-13000-exec-5] INFO  p.a.c.ArtifactsAPIController - longDescription = null
12:13:52.228 [http-nio-13000-exec-5] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/osapi] threw exception [Request processing failed: java.lang.NullPointerException: Cannot read the array length because "<local11>" is null] with root cause
java.lang.NullPointerException: Cannot read the array length because "<local11>" is null
	at portal.api.controller.ArtifactsAPIController.updateProductMetadata(ArtifactsAPIController.java:1024)
	at portal.api.controller.ArtifactsAPIController.updateVxFMetadata(ArtifactsAPIController.java:882)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
….
```

The issue relies on the line 882 of the ArtifactsAPIController java class:

``` java
for (MultipartFile shot : screenshots) {
	String shotFileNamePosted = shot.getOriginalFilename(); // AttachmentUtil.getFileName(shot.getHeaders());
	logger.info("Found screenshot image shotFileNamePosted = " + shotFileNamePosted);
	logger.info("shotFileNamePosted = " + shotFileNamePosted);
	if (!shotFileNamePosted.equals("")) {
		shotFileNamePosted = "shot" + i + "_" + shotFileNamePosted;
		String shotfilepath = AttachmentUtil.saveFile(shot, tempDir + shotFileNamePosted);
		logger.info("shotfilepath saved to = " + shotfilepath);
		shotfilepath = endpointUrl.toString().replace("http:", "") + "/images/" + prevProduct.getUuid() + "/"
				+ shotFileNamePosted;
		screenshotsFilenames += shotfilepath + ",";
		i++;
	}
}
```

This code is invoked by the `/admin/vxfs/{bid}` endpoint method. The signature of the method that implements/provides this endpoint is the following:

``` java
@PutMapping(value = "/admin/vxfs/{bid}", produces = "application/json", consumes = "multipart/form-data")
	public ResponseEntity<?> updateVxFMetadata(@PathVariable("bid") int bid, @ModelAttribute("vxf") String avxf,
			@RequestParam(name = "prodIcon", required = false) MultipartFile prodIcon,
			@RequestParam(name = "prodFile", required = false) MultipartFile prodFile,
			@RequestParam(name = "screenshots", required = false, defaultValue = "") MultipartFile[] screenshots,
			HttpServletRequest request) throws ForbiddenException {
```

As one may see, the `screenshots` value is optional and thus can be `null`. This function later invokes the `updateProductMetadata`, which contains the for each code previously presented. As `screenshots` is `null`, it is impossible to execute that for each. Therefore, the error returned by the Portal API.

**Comment by ctranoris** [comment]
thanks rafael. cc @kostistr @Ioannischatzis
